services:
  firestore:
    image: andreysenov/firebase-tools:latest
    working_dir: /workspace
    command: >
      firebase emulators:start
      --config /workspace/infra/local/firebase.json
      --only firestore,ui
      --project demo-inventory
      --import=/workspace/.firebase-data
      --export-on-exit
    ports:
      - "8080:8080"
      - "4000:4000"
    volumes:
      - ./:/workspace
      - firestore_data:/workspace/.firebase-data

  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    depends_on:
      - firestore
      - mailhog
    ports:
      - "8000:8080"
    environment:
      FIRESTORE_EMULATOR_HOST: firestore:8080
      GRPC_DNS_RESOLVER: native
      GOOGLE_CLOUD_PROJECT: demo-inventory
      GCP_PROJECT_ID: demo-inventory
      JWT_SECRET: dev-secret
      JWT_EXPIRES_MINUTES: "60"
      JWT_ALGORITHM: HS256

  seed:
    image: python:3.13-slim
    working_dir: /workspace
    depends_on:
      - firestore
    environment:
      FIRESTORE_EMULATOR_HOST: firestore:8080
      GRPC_DNS_RESOLVER: native
      GOOGLE_CLOUD_PROJECT: demo-inventory
    volumes:
      - ./:/workspace
    command: >
      sh -lc "
        pip install --no-cache-dir google-cloud-firestore &&
        python infra/local/seed_firestore_emulator.py
      "

  orders_listener:
    image: python:3.13-slim
    working_dir: /workspace/services/orders_listener/src
    depends_on:
      - firestore
      - mailhog
    ports:
      - "8081:8080"
    environment:
      FIRESTORE_EMULATOR_HOST: firestore:8080
      GRPC_DNS_RESOLVER: native
      GCP_PROJECT_ID: demo-inventory
      ORDERS_COLLECTION: Orders
      PRODUCTS_COLLECTION: Products
      SMTP_HOST: mailhog
      SMTP_PORT: "1025"
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SMTP_FROM: "test@example.com"
      SMTP_USE_TLS: "false"
    volumes:
      - ./:/workspace
    command: >
      sh -lc "
        pip install --no-cache-dir -r requirements.txt &&
        functions-framework --target=orders_listener_http --port=8080
      "

  # This bridge is required in order to Firestore triggers
  # the order listener event
  orders_listener_bridge:
    image: python:3.13-slim
    working_dir: /workspace/services/orders_listener/bridge
    depends_on:
      - firestore
      - orders_listener
    environment:
      FIRESTORE_EMULATOR_HOST: firestore:8080
      GRPC_DNS_RESOLVER: native
      GOOGLE_CLOUD_PROJECT: demo-inventory
      GCP_PROJECT_ID: demo-inventory
      ORDERS_COLLECTION: Orders
      FUNCTIONS_URL: http://orders_listener:8080/
    volumes:
      - ./:/workspace
    command: >
      sh -lc "
        pip install --no-cache-dir -r requirements.txt &&
        python bridge.py
      "

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  firestore_data: